# MODEL
model_name_or_path: klue/bert-base
saved_model_path: /opt/ml/models/train_dataset/MODEL_NAME
config_name: 
tokenizer_name: 

# DATATRAINING
train_dataset_name: /opt/ml/input/data/train_dataset
test_dataset_name: /opt/ml/input/data/test_dataset
overwrite_cache: False
preprocessing_num_workers: 
max_seq_length: 384
pad_to_max_length: False
doc_stride: 128
max_answer_length: 30
eval_retrieval: True
num_clusters: 64
top_k_retrieval: 10
use_faiss: False

# TRAINING
train_output_dir: /opt/ml/models/train_dataset
test_output_dir: /opt/ml/outputs/test_dataset
do_train: True
do_eval: True
seed: 42
total_save_model: 
max_epoch: 3.0
learning_rate: 5.0e-5
batch_size: 8
warmup_steps: 0
weight_decay: 0.0

# CUSTOM
wandb_project: mrc
wandb_name: test1